#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gastro
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GastroDB")]
	public partial class LinqGastroDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProdukty(Produkty instance);
    partial void UpdateProdukty(Produkty instance);
    partial void DeleteProdukty(Produkty instance);
    partial void InsertAminokwasy(Aminokwasy instance);
    partial void UpdateAminokwasy(Aminokwasy instance);
    partial void DeleteAminokwasy(Aminokwasy instance);
    #endregion
		
		public LinqGastroDataContext() : 
				base(global::Gastro.Properties.Settings.Default.GastroDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqGastroDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqGastroDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqGastroDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqGastroDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Energia> Energias
		{
			get
			{
				return this.GetTable<Energia>();
			}
		}
		
		public System.Data.Linq.Table<Kw_tluszcz_jednonienasyc> Kw_tluszcz_jednonienasycs
		{
			get
			{
				return this.GetTable<Kw_tluszcz_jednonienasyc>();
			}
		}
		
		public System.Data.Linq.Table<Kw_tluszcz_nasyc> Kw_tluszcz_nasycs
		{
			get
			{
				return this.GetTable<Kw_tluszcz_nasyc>();
			}
		}
		
		public System.Data.Linq.Table<Kw_tluszcz_wielonienasyc> Kw_tluszcz_wielonienasycs
		{
			get
			{
				return this.GetTable<Kw_tluszcz_wielonienasyc>();
			}
		}
		
		public System.Data.Linq.Table<Produkty> Produkties
		{
			get
			{
				return this.GetTable<Produkty>();
			}
		}
		
		public System.Data.Linq.Table<Skladniki_mineralne> Skladniki_mineralnes
		{
			get
			{
				return this.GetTable<Skladniki_mineralne>();
			}
		}
		
		public System.Data.Linq.Table<Wartosc_energetyczna> Wartosc_energetycznas
		{
			get
			{
				return this.GetTable<Wartosc_energetyczna>();
			}
		}
		
		public System.Data.Linq.Table<Weglowodany> Weglowodanies
		{
			get
			{
				return this.GetTable<Weglowodany>();
			}
		}
		
		public System.Data.Linq.Table<Witaminy> Witaminies
		{
			get
			{
				return this.GetTable<Witaminy>();
			}
		}
		
		public System.Data.Linq.Table<Aminokwasy> Aminokwasies
		{
			get
			{
				return this.GetTable<Aminokwasy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Energia")]
	public partial class Energia
	{
		
		private string _numer_kodowy;
		
		private int _bialko;
		
		private int _tluszcz;
		
		private int _weglowodany;
		
		public Energia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bialko", DbType="Int NOT NULL")]
		public int bialko
		{
			get
			{
				return this._bialko;
			}
			set
			{
				if ((this._bialko != value))
				{
					this._bialko = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tluszcz", DbType="Int NOT NULL")]
		public int tluszcz
		{
			get
			{
				return this._tluszcz;
			}
			set
			{
				if ((this._tluszcz != value))
				{
					this._tluszcz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weglowodany", DbType="Int NOT NULL")]
		public int weglowodany
		{
			get
			{
				return this._weglowodany;
			}
			set
			{
				if ((this._weglowodany != value))
				{
					this._weglowodany = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kw_tluszcz_jednonienasyc")]
	public partial class Kw_tluszcz_jednonienasyc
	{
		
		private string _numer_kodowy;
		
		private float _C14_1;
		
		private float _C15_1;
		
		private float _C16_1;
		
		private float _C17_1;
		
		private float _C18_1;
		
		private float _C20_1;
		
		private float _C22_1;
		
		public Kw_tluszcz_jednonienasyc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C14_1", DbType="Real NOT NULL")]
		public float C14_1
		{
			get
			{
				return this._C14_1;
			}
			set
			{
				if ((this._C14_1 != value))
				{
					this._C14_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C15_1", DbType="Real NOT NULL")]
		public float C15_1
		{
			get
			{
				return this._C15_1;
			}
			set
			{
				if ((this._C15_1 != value))
				{
					this._C15_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C16_1", DbType="Real NOT NULL")]
		public float C16_1
		{
			get
			{
				return this._C16_1;
			}
			set
			{
				if ((this._C16_1 != value))
				{
					this._C16_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C17_1", DbType="Real NOT NULL")]
		public float C17_1
		{
			get
			{
				return this._C17_1;
			}
			set
			{
				if ((this._C17_1 != value))
				{
					this._C17_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C18_1", DbType="Real NOT NULL")]
		public float C18_1
		{
			get
			{
				return this._C18_1;
			}
			set
			{
				if ((this._C18_1 != value))
				{
					this._C18_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C20_1", DbType="Real NOT NULL")]
		public float C20_1
		{
			get
			{
				return this._C20_1;
			}
			set
			{
				if ((this._C20_1 != value))
				{
					this._C20_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C22_1", DbType="Real NOT NULL")]
		public float C22_1
		{
			get
			{
				return this._C22_1;
			}
			set
			{
				if ((this._C22_1 != value))
				{
					this._C22_1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kw_tluszcz_nasyc")]
	public partial class Kw_tluszcz_nasyc
	{
		
		private string _numer_kodowy;
		
		private float _C4_0;
		
		private float _C6_0;
		
		private float _C8_0;
		
		private float _C10_0;
		
		private float _C12_0;
		
		private float _C14_0;
		
		private float _C15_0;
		
		private float _C16_0;
		
		private float _C17_0;
		
		private float _C18_0;
		
		private float _C20_0;
		
		public Kw_tluszcz_nasyc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C4_0", DbType="Real NOT NULL")]
		public float C4_0
		{
			get
			{
				return this._C4_0;
			}
			set
			{
				if ((this._C4_0 != value))
				{
					this._C4_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C6_0", DbType="Real NOT NULL")]
		public float C6_0
		{
			get
			{
				return this._C6_0;
			}
			set
			{
				if ((this._C6_0 != value))
				{
					this._C6_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C8_0", DbType="Real NOT NULL")]
		public float C8_0
		{
			get
			{
				return this._C8_0;
			}
			set
			{
				if ((this._C8_0 != value))
				{
					this._C8_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C10_0", DbType="Real NOT NULL")]
		public float C10_0
		{
			get
			{
				return this._C10_0;
			}
			set
			{
				if ((this._C10_0 != value))
				{
					this._C10_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C12_0", DbType="Real NOT NULL")]
		public float C12_0
		{
			get
			{
				return this._C12_0;
			}
			set
			{
				if ((this._C12_0 != value))
				{
					this._C12_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C14_0", DbType="Real NOT NULL")]
		public float C14_0
		{
			get
			{
				return this._C14_0;
			}
			set
			{
				if ((this._C14_0 != value))
				{
					this._C14_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C15_0", DbType="Real NOT NULL")]
		public float C15_0
		{
			get
			{
				return this._C15_0;
			}
			set
			{
				if ((this._C15_0 != value))
				{
					this._C15_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C16_0", DbType="Real NOT NULL")]
		public float C16_0
		{
			get
			{
				return this._C16_0;
			}
			set
			{
				if ((this._C16_0 != value))
				{
					this._C16_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C17_0", DbType="Real NOT NULL")]
		public float C17_0
		{
			get
			{
				return this._C17_0;
			}
			set
			{
				if ((this._C17_0 != value))
				{
					this._C17_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C18_0", DbType="Real NOT NULL")]
		public float C18_0
		{
			get
			{
				return this._C18_0;
			}
			set
			{
				if ((this._C18_0 != value))
				{
					this._C18_0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C20_0", DbType="Real NOT NULL")]
		public float C20_0
		{
			get
			{
				return this._C20_0;
			}
			set
			{
				if ((this._C20_0 != value))
				{
					this._C20_0 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kw_tluszcz_wielonienasyc")]
	public partial class Kw_tluszcz_wielonienasyc
	{
		
		private string _numer_kodowy;
		
		private float _C18_2;
		
		private float _C18_3;
		
		private float _C18_4;
		
		private float _C20_3;
		
		private float _C20_4;
		
		private float _C20_5;
		
		private float _C22_5;
		
		private float _C22_6;
		
		public Kw_tluszcz_wielonienasyc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C18_2", DbType="Real NOT NULL")]
		public float C18_2
		{
			get
			{
				return this._C18_2;
			}
			set
			{
				if ((this._C18_2 != value))
				{
					this._C18_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C18_3", DbType="Real NOT NULL")]
		public float C18_3
		{
			get
			{
				return this._C18_3;
			}
			set
			{
				if ((this._C18_3 != value))
				{
					this._C18_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C18_4", DbType="Real NOT NULL")]
		public float C18_4
		{
			get
			{
				return this._C18_4;
			}
			set
			{
				if ((this._C18_4 != value))
				{
					this._C18_4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C20_3", DbType="Real NOT NULL")]
		public float C20_3
		{
			get
			{
				return this._C20_3;
			}
			set
			{
				if ((this._C20_3 != value))
				{
					this._C20_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C20_4", DbType="Real NOT NULL")]
		public float C20_4
		{
			get
			{
				return this._C20_4;
			}
			set
			{
				if ((this._C20_4 != value))
				{
					this._C20_4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C20_5", DbType="Real NOT NULL")]
		public float C20_5
		{
			get
			{
				return this._C20_5;
			}
			set
			{
				if ((this._C20_5 != value))
				{
					this._C20_5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C22_5", DbType="Real NOT NULL")]
		public float C22_5
		{
			get
			{
				return this._C22_5;
			}
			set
			{
				if ((this._C22_5 != value))
				{
					this._C22_5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C22_6", DbType="Real NOT NULL")]
		public float C22_6
		{
			get
			{
				return this._C22_6;
			}
			set
			{
				if ((this._C22_6 != value))
				{
					this._C22_6 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkty")]
	public partial class Produkty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _numer_kodowy;
		
		private string _nazwa_produktu;
		
		private int _odpadki;
		
		private float _bialko_zwierzece;
		
		private float _bialko_roslinne;
		
		private float _woda;
		
		private int _choresterol;
		
		private float _tluszcz;
		
		private float _popiol;
		
		private EntityRef<Aminokwasy> _Aminokwasy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnumer_kodowyChanging(string value);
    partial void Onnumer_kodowyChanged();
    partial void Onnazwa_produktuChanging(string value);
    partial void Onnazwa_produktuChanged();
    partial void OnodpadkiChanging(int value);
    partial void OnodpadkiChanged();
    partial void Onbialko_zwierzeceChanging(float value);
    partial void Onbialko_zwierzeceChanged();
    partial void Onbialko_roslinneChanging(float value);
    partial void Onbialko_roslinneChanged();
    partial void OnwodaChanging(float value);
    partial void OnwodaChanged();
    partial void OnchoresterolChanging(int value);
    partial void OnchoresterolChanged();
    partial void OntluszczChanging(float value);
    partial void OntluszczChanged();
    partial void OnpopiolChanging(float value);
    partial void OnpopiolChanged();
    #endregion
		
		public Produkty()
		{
			this._Aminokwasy = default(EntityRef<Aminokwasy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this.Onnumer_kodowyChanging(value);
					this.SendPropertyChanging();
					this._numer_kodowy = value;
					this.SendPropertyChanged("numer_kodowy");
					this.Onnumer_kodowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_produktu", DbType="NChar(45) NOT NULL", CanBeNull=false)]
		public string nazwa_produktu
		{
			get
			{
				return this._nazwa_produktu;
			}
			set
			{
				if ((this._nazwa_produktu != value))
				{
					this.Onnazwa_produktuChanging(value);
					this.SendPropertyChanging();
					this._nazwa_produktu = value;
					this.SendPropertyChanged("nazwa_produktu");
					this.Onnazwa_produktuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odpadki", DbType="Int NOT NULL")]
		public int odpadki
		{
			get
			{
				return this._odpadki;
			}
			set
			{
				if ((this._odpadki != value))
				{
					this.OnodpadkiChanging(value);
					this.SendPropertyChanging();
					this._odpadki = value;
					this.SendPropertyChanged("odpadki");
					this.OnodpadkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bialko_zwierzece", DbType="Real NOT NULL")]
		public float bialko_zwierzece
		{
			get
			{
				return this._bialko_zwierzece;
			}
			set
			{
				if ((this._bialko_zwierzece != value))
				{
					this.Onbialko_zwierzeceChanging(value);
					this.SendPropertyChanging();
					this._bialko_zwierzece = value;
					this.SendPropertyChanged("bialko_zwierzece");
					this.Onbialko_zwierzeceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bialko_roslinne", DbType="Real NOT NULL")]
		public float bialko_roslinne
		{
			get
			{
				return this._bialko_roslinne;
			}
			set
			{
				if ((this._bialko_roslinne != value))
				{
					this.Onbialko_roslinneChanging(value);
					this.SendPropertyChanging();
					this._bialko_roslinne = value;
					this.SendPropertyChanged("bialko_roslinne");
					this.Onbialko_roslinneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_woda", DbType="Real NOT NULL")]
		public float woda
		{
			get
			{
				return this._woda;
			}
			set
			{
				if ((this._woda != value))
				{
					this.OnwodaChanging(value);
					this.SendPropertyChanging();
					this._woda = value;
					this.SendPropertyChanged("woda");
					this.OnwodaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choresterol", DbType="Int NOT NULL")]
		public int choresterol
		{
			get
			{
				return this._choresterol;
			}
			set
			{
				if ((this._choresterol != value))
				{
					this.OnchoresterolChanging(value);
					this.SendPropertyChanging();
					this._choresterol = value;
					this.SendPropertyChanged("choresterol");
					this.OnchoresterolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tluszcz", DbType="Real NOT NULL")]
		public float tluszcz
		{
			get
			{
				return this._tluszcz;
			}
			set
			{
				if ((this._tluszcz != value))
				{
					this.OntluszczChanging(value);
					this.SendPropertyChanging();
					this._tluszcz = value;
					this.SendPropertyChanged("tluszcz");
					this.OntluszczChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popiol", DbType="Real NOT NULL")]
		public float popiol
		{
			get
			{
				return this._popiol;
			}
			set
			{
				if ((this._popiol != value))
				{
					this.OnpopiolChanging(value);
					this.SendPropertyChanging();
					this._popiol = value;
					this.SendPropertyChanged("popiol");
					this.OnpopiolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkty_Aminokwasy", Storage="_Aminokwasy", ThisKey="numer_kodowy", OtherKey="numer_kodowy", IsUnique=true, IsForeignKey=false)]
		public Aminokwasy Aminokwasy
		{
			get
			{
				return this._Aminokwasy.Entity;
			}
			set
			{
				Aminokwasy previousValue = this._Aminokwasy.Entity;
				if (((previousValue != value) 
							|| (this._Aminokwasy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aminokwasy.Entity = null;
						previousValue.Produkty = null;
					}
					this._Aminokwasy.Entity = value;
					if ((value != null))
					{
						value.Produkty = this;
					}
					this.SendPropertyChanged("Aminokwasy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Skladniki_mineralne")]
	public partial class Skladniki_mineralne
	{
		
		private string _numer_kodowy;
		
		private float _sod;
		
		private float _potas;
		
		private float _wapn;
		
		private float _fosfor;
		
		private float _magnez;
		
		private float _zelazo;
		
		private float _cynk;
		
		private float _miedz;
		
		private float _mangan;
		
		public Skladniki_mineralne()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sod", DbType="Real NOT NULL")]
		public float sod
		{
			get
			{
				return this._sod;
			}
			set
			{
				if ((this._sod != value))
				{
					this._sod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_potas", DbType="Real NOT NULL")]
		public float potas
		{
			get
			{
				return this._potas;
			}
			set
			{
				if ((this._potas != value))
				{
					this._potas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wapn", DbType="Real NOT NULL")]
		public float wapn
		{
			get
			{
				return this._wapn;
			}
			set
			{
				if ((this._wapn != value))
				{
					this._wapn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fosfor", DbType="Real NOT NULL")]
		public float fosfor
		{
			get
			{
				return this._fosfor;
			}
			set
			{
				if ((this._fosfor != value))
				{
					this._fosfor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magnez", DbType="Real NOT NULL")]
		public float magnez
		{
			get
			{
				return this._magnez;
			}
			set
			{
				if ((this._magnez != value))
				{
					this._magnez = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zelazo", DbType="Real NOT NULL")]
		public float zelazo
		{
			get
			{
				return this._zelazo;
			}
			set
			{
				if ((this._zelazo != value))
				{
					this._zelazo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cynk", DbType="Real NOT NULL")]
		public float cynk
		{
			get
			{
				return this._cynk;
			}
			set
			{
				if ((this._cynk != value))
				{
					this._cynk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miedz", DbType="Real NOT NULL")]
		public float miedz
		{
			get
			{
				return this._miedz;
			}
			set
			{
				if ((this._miedz != value))
				{
					this._miedz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mangan", DbType="Real NOT NULL")]
		public float mangan
		{
			get
			{
				return this._mangan;
			}
			set
			{
				if ((this._mangan != value))
				{
					this._mangan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wartosc_energetyczna")]
	public partial class Wartosc_energetyczna
	{
		
		private string _numer_kodowy;
		
		private int _KJ;
		
		private int _kcal;
		
		public Wartosc_energetyczna()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KJ", DbType="Int NOT NULL")]
		public int KJ
		{
			get
			{
				return this._KJ;
			}
			set
			{
				if ((this._KJ != value))
				{
					this._KJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kcal", DbType="Int NOT NULL")]
		public int kcal
		{
			get
			{
				return this._kcal;
			}
			set
			{
				if ((this._kcal != value))
				{
					this._kcal = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Weglowodany")]
	public partial class Weglowodany
	{
		
		private string _numer_kodowy;
		
		private double _sacharoza;
		
		private double _laktoza;
		
		private double _skrobia;
		
		private double _blonnik_pokarmowy;
		
		public Weglowodany()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sacharoza", DbType="Float NOT NULL")]
		public double sacharoza
		{
			get
			{
				return this._sacharoza;
			}
			set
			{
				if ((this._sacharoza != value))
				{
					this._sacharoza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_laktoza", DbType="Float NOT NULL")]
		public double laktoza
		{
			get
			{
				return this._laktoza;
			}
			set
			{
				if ((this._laktoza != value))
				{
					this._laktoza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skrobia", DbType="Float NOT NULL")]
		public double skrobia
		{
			get
			{
				return this._skrobia;
			}
			set
			{
				if ((this._skrobia != value))
				{
					this._skrobia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blonnik_pokarmowy", DbType="Float NOT NULL")]
		public double blonnik_pokarmowy
		{
			get
			{
				return this._blonnik_pokarmowy;
			}
			set
			{
				if ((this._blonnik_pokarmowy != value))
				{
					this._blonnik_pokarmowy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Witaminy")]
	public partial class Witaminy
	{
		
		private string _numer_kodowy;
		
		private float _ek_retinolu;
		
		private float _retinol;
		
		private float _beta_karoten;
		
		private float _D;
		
		private float _E;
		
		private float _tiamina;
		
		private float _ryboflawina;
		
		private float _niacyna;
		
		private float _B6;
		
		private float _foliany;
		
		private float _B12;
		
		private float _C;
		
		public Witaminy()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					this._numer_kodowy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ek_retinolu", DbType="Real NOT NULL")]
		public float ek_retinolu
		{
			get
			{
				return this._ek_retinolu;
			}
			set
			{
				if ((this._ek_retinolu != value))
				{
					this._ek_retinolu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_retinol", DbType="Real NOT NULL")]
		public float retinol
		{
			get
			{
				return this._retinol;
			}
			set
			{
				if ((this._retinol != value))
				{
					this._retinol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beta_karoten", DbType="Real NOT NULL")]
		public float beta_karoten
		{
			get
			{
				return this._beta_karoten;
			}
			set
			{
				if ((this._beta_karoten != value))
				{
					this._beta_karoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Real NOT NULL")]
		public float D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Real NOT NULL")]
		public float E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiamina", DbType="Real NOT NULL")]
		public float tiamina
		{
			get
			{
				return this._tiamina;
			}
			set
			{
				if ((this._tiamina != value))
				{
					this._tiamina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ryboflawina", DbType="Real NOT NULL")]
		public float ryboflawina
		{
			get
			{
				return this._ryboflawina;
			}
			set
			{
				if ((this._ryboflawina != value))
				{
					this._ryboflawina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niacyna", DbType="Real NOT NULL")]
		public float niacyna
		{
			get
			{
				return this._niacyna;
			}
			set
			{
				if ((this._niacyna != value))
				{
					this._niacyna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B6", DbType="Real NOT NULL")]
		public float B6
		{
			get
			{
				return this._B6;
			}
			set
			{
				if ((this._B6 != value))
				{
					this._B6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foliany", DbType="Real NOT NULL")]
		public float foliany
		{
			get
			{
				return this._foliany;
			}
			set
			{
				if ((this._foliany != value))
				{
					this._foliany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B12", DbType="Real NOT NULL")]
		public float B12
		{
			get
			{
				return this._B12;
			}
			set
			{
				if ((this._B12 != value))
				{
					this._B12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Real NOT NULL")]
		public float C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aminokwasy")]
	public partial class Aminokwasy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _numer_kodowy;
		
		private int _izoleucyna;
		
		private int _leucyna;
		
		private int _lizyna;
		
		private int _metionina;
		
		private int _cystyna;
		
		private int _fenyloalanina;
		
		private int _tyrozyna;
		
		private int _treonina;
		
		private int _tryptofan;
		
		private int _walina;
		
		private int _arginina;
		
		private int _histydyna;
		
		private int _alanina;
		
		private int _kwas_asparaginowy;
		
		private int _kwas_glutaminowy;
		
		private int _glicyna;
		
		private int _prolina;
		
		private int _seryna;
		
		private EntityRef<Produkty> _Produkty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnumer_kodowyChanging(string value);
    partial void Onnumer_kodowyChanged();
    partial void OnizoleucynaChanging(int value);
    partial void OnizoleucynaChanged();
    partial void OnleucynaChanging(int value);
    partial void OnleucynaChanged();
    partial void OnlizynaChanging(int value);
    partial void OnlizynaChanged();
    partial void OnmetioninaChanging(int value);
    partial void OnmetioninaChanged();
    partial void OncystynaChanging(int value);
    partial void OncystynaChanged();
    partial void OnfenyloalaninaChanging(int value);
    partial void OnfenyloalaninaChanged();
    partial void OntyrozynaChanging(int value);
    partial void OntyrozynaChanged();
    partial void OntreoninaChanging(int value);
    partial void OntreoninaChanged();
    partial void OntryptofanChanging(int value);
    partial void OntryptofanChanged();
    partial void OnwalinaChanging(int value);
    partial void OnwalinaChanged();
    partial void OnargininaChanging(int value);
    partial void OnargininaChanged();
    partial void OnhistydynaChanging(int value);
    partial void OnhistydynaChanged();
    partial void OnalaninaChanging(int value);
    partial void OnalaninaChanged();
    partial void Onkwas_asparaginowyChanging(int value);
    partial void Onkwas_asparaginowyChanged();
    partial void Onkwas_glutaminowyChanging(int value);
    partial void Onkwas_glutaminowyChanged();
    partial void OnglicynaChanging(int value);
    partial void OnglicynaChanged();
    partial void OnprolinaChanging(int value);
    partial void OnprolinaChanged();
    partial void OnserynaChanging(int value);
    partial void OnserynaChanged();
    #endregion
		
		public Aminokwasy()
		{
			this._Produkty = default(EntityRef<Produkty>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_kodowy", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string numer_kodowy
		{
			get
			{
				return this._numer_kodowy;
			}
			set
			{
				if ((this._numer_kodowy != value))
				{
					if (this._Produkty.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnumer_kodowyChanging(value);
					this.SendPropertyChanging();
					this._numer_kodowy = value;
					this.SendPropertyChanged("numer_kodowy");
					this.Onnumer_kodowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_izoleucyna", DbType="Int NOT NULL")]
		public int izoleucyna
		{
			get
			{
				return this._izoleucyna;
			}
			set
			{
				if ((this._izoleucyna != value))
				{
					this.OnizoleucynaChanging(value);
					this.SendPropertyChanging();
					this._izoleucyna = value;
					this.SendPropertyChanged("izoleucyna");
					this.OnizoleucynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leucyna", DbType="Int NOT NULL")]
		public int leucyna
		{
			get
			{
				return this._leucyna;
			}
			set
			{
				if ((this._leucyna != value))
				{
					this.OnleucynaChanging(value);
					this.SendPropertyChanging();
					this._leucyna = value;
					this.SendPropertyChanged("leucyna");
					this.OnleucynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lizyna", DbType="Int NOT NULL")]
		public int lizyna
		{
			get
			{
				return this._lizyna;
			}
			set
			{
				if ((this._lizyna != value))
				{
					this.OnlizynaChanging(value);
					this.SendPropertyChanging();
					this._lizyna = value;
					this.SendPropertyChanged("lizyna");
					this.OnlizynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metionina", DbType="Int NOT NULL")]
		public int metionina
		{
			get
			{
				return this._metionina;
			}
			set
			{
				if ((this._metionina != value))
				{
					this.OnmetioninaChanging(value);
					this.SendPropertyChanging();
					this._metionina = value;
					this.SendPropertyChanged("metionina");
					this.OnmetioninaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cystyna", DbType="Int NOT NULL")]
		public int cystyna
		{
			get
			{
				return this._cystyna;
			}
			set
			{
				if ((this._cystyna != value))
				{
					this.OncystynaChanging(value);
					this.SendPropertyChanging();
					this._cystyna = value;
					this.SendPropertyChanged("cystyna");
					this.OncystynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fenyloalanina", DbType="Int NOT NULL")]
		public int fenyloalanina
		{
			get
			{
				return this._fenyloalanina;
			}
			set
			{
				if ((this._fenyloalanina != value))
				{
					this.OnfenyloalaninaChanging(value);
					this.SendPropertyChanging();
					this._fenyloalanina = value;
					this.SendPropertyChanged("fenyloalanina");
					this.OnfenyloalaninaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tyrozyna", DbType="Int NOT NULL")]
		public int tyrozyna
		{
			get
			{
				return this._tyrozyna;
			}
			set
			{
				if ((this._tyrozyna != value))
				{
					this.OntyrozynaChanging(value);
					this.SendPropertyChanging();
					this._tyrozyna = value;
					this.SendPropertyChanged("tyrozyna");
					this.OntyrozynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treonina", DbType="Int NOT NULL")]
		public int treonina
		{
			get
			{
				return this._treonina;
			}
			set
			{
				if ((this._treonina != value))
				{
					this.OntreoninaChanging(value);
					this.SendPropertyChanging();
					this._treonina = value;
					this.SendPropertyChanged("treonina");
					this.OntreoninaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tryptofan", DbType="Int NOT NULL")]
		public int tryptofan
		{
			get
			{
				return this._tryptofan;
			}
			set
			{
				if ((this._tryptofan != value))
				{
					this.OntryptofanChanging(value);
					this.SendPropertyChanging();
					this._tryptofan = value;
					this.SendPropertyChanged("tryptofan");
					this.OntryptofanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_walina", DbType="Int NOT NULL")]
		public int walina
		{
			get
			{
				return this._walina;
			}
			set
			{
				if ((this._walina != value))
				{
					this.OnwalinaChanging(value);
					this.SendPropertyChanging();
					this._walina = value;
					this.SendPropertyChanged("walina");
					this.OnwalinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arginina", DbType="Int NOT NULL")]
		public int arginina
		{
			get
			{
				return this._arginina;
			}
			set
			{
				if ((this._arginina != value))
				{
					this.OnargininaChanging(value);
					this.SendPropertyChanging();
					this._arginina = value;
					this.SendPropertyChanged("arginina");
					this.OnargininaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_histydyna", DbType="Int NOT NULL")]
		public int histydyna
		{
			get
			{
				return this._histydyna;
			}
			set
			{
				if ((this._histydyna != value))
				{
					this.OnhistydynaChanging(value);
					this.SendPropertyChanging();
					this._histydyna = value;
					this.SendPropertyChanged("histydyna");
					this.OnhistydynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alanina", DbType="Int NOT NULL")]
		public int alanina
		{
			get
			{
				return this._alanina;
			}
			set
			{
				if ((this._alanina != value))
				{
					this.OnalaninaChanging(value);
					this.SendPropertyChanging();
					this._alanina = value;
					this.SendPropertyChanged("alanina");
					this.OnalaninaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwas_asparaginowy", DbType="Int NOT NULL")]
		public int kwas_asparaginowy
		{
			get
			{
				return this._kwas_asparaginowy;
			}
			set
			{
				if ((this._kwas_asparaginowy != value))
				{
					this.Onkwas_asparaginowyChanging(value);
					this.SendPropertyChanging();
					this._kwas_asparaginowy = value;
					this.SendPropertyChanged("kwas_asparaginowy");
					this.Onkwas_asparaginowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwas_glutaminowy", DbType="Int NOT NULL")]
		public int kwas_glutaminowy
		{
			get
			{
				return this._kwas_glutaminowy;
			}
			set
			{
				if ((this._kwas_glutaminowy != value))
				{
					this.Onkwas_glutaminowyChanging(value);
					this.SendPropertyChanging();
					this._kwas_glutaminowy = value;
					this.SendPropertyChanged("kwas_glutaminowy");
					this.Onkwas_glutaminowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glicyna", DbType="Int NOT NULL")]
		public int glicyna
		{
			get
			{
				return this._glicyna;
			}
			set
			{
				if ((this._glicyna != value))
				{
					this.OnglicynaChanging(value);
					this.SendPropertyChanging();
					this._glicyna = value;
					this.SendPropertyChanged("glicyna");
					this.OnglicynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prolina", DbType="Int NOT NULL")]
		public int prolina
		{
			get
			{
				return this._prolina;
			}
			set
			{
				if ((this._prolina != value))
				{
					this.OnprolinaChanging(value);
					this.SendPropertyChanging();
					this._prolina = value;
					this.SendPropertyChanged("prolina");
					this.OnprolinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seryna", DbType="Int NOT NULL")]
		public int seryna
		{
			get
			{
				return this._seryna;
			}
			set
			{
				if ((this._seryna != value))
				{
					this.OnserynaChanging(value);
					this.SendPropertyChanging();
					this._seryna = value;
					this.SendPropertyChanged("seryna");
					this.OnserynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkty_Aminokwasy", Storage="_Produkty", ThisKey="numer_kodowy", OtherKey="numer_kodowy", IsForeignKey=true)]
		public Produkty Produkty
		{
			get
			{
				return this._Produkty.Entity;
			}
			set
			{
				Produkty previousValue = this._Produkty.Entity;
				if (((previousValue != value) 
							|| (this._Produkty.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produkty.Entity = null;
						previousValue.Aminokwasy = null;
					}
					this._Produkty.Entity = value;
					if ((value != null))
					{
						value.Aminokwasy = this;
						this._numer_kodowy = value.numer_kodowy;
					}
					else
					{
						this._numer_kodowy = default(string);
					}
					this.SendPropertyChanged("Produkty");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
